import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePicture from "../../public/images/profile/profilepicture1.jpg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import bulb from "../../public/images/svgs/bulb.svg";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout>
          <div className="flex item-center justify-between w-full ">
            <div className="w-1/2">
              <Image
                src={profilePicture}
                alt="portfoliopic1"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Engineering Interfaces That Spark Joy and Engagement!"
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium ">
                I'm a frontend developer with a passion for creating beautiful
                and intuitive user interfaces. Explore my latest projects and
                articles, showcasing my expertise in React.js and web
                development
              </p>

              <div className="flex items-center self-start mt-2 ">
                <Link
                  href="/FurkanFiratResume.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark duration-500 ease-in-out"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:furkan.0096@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline "
                >
                  Contact
                </Link>
              </div>
              <div className="absolute right-8 bottom-8 inline-block w-28">
                <Image src={bulb} alt="portfolio" className="w-full h-auto" />
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
      </main>
    </>
  );
}
